#!/bin/bash
strt_time=$(date +%s.%2N)
stamplist=$(cat .stamplist)
count=0

# stamp loop
for line in $stamplist; do
	# parse
	path=$(echo "$line" | cut -d ':' -f 1)
	stamp_path=$(echo "$line" | cut -d ':' -f 2)
	if [ "$(cat $stamp_path)" = "" ]; then
		continue
	fi
	skip_bytes=$(echo "$line" | cut -d ':' -f 3)
	new_skip_bytes=$(wc -c $stamp_path | cut -d ' ' -f 1)

	# destamp/restamp and update stamplist
	tmp=$(mktemp)
	cat $stamp_path >> $tmp
	dd if=$path of=$tmp bs=1 skip=$skip_bytes oflag=append conv=notrunc status=none
	sed -i "s#$line#$path:$stamp_path:$new_skip_bytes#" .stamplist
	cat $tmp > $path
	rm -f $tmp
	count=$(( $count + 1 ))
done

end_time=$(date +%s.%2N)
exec_time=$(echo "$end_time - $strt_time" | bc)
echo -ne "\033[1;97mStamped $count files in "
printf "%.2f seconds\n" $exec_time
