#!/bin/bash

# prepare data and files
touch rootfile.c
mkdir subdir
touch subdir/subdirfile.h
touch .stamp
touch .stamplist
touch should-not-stamp
echo "TEST-STAMP" > .stamp
echo "rootfile.c" >> .stamplist
echo "subdir/subdirfile.h" >> .stamplist

# tests
echo -e "\033[1;97mTesting \033[1;32mstamp\033[1;97m script\n"
../stamp > /dev/null
echo -n "file in root directory "
if [ "$(cat rootfile.c)" = "TEST-STAMP" ]; then
	echo -e "		\033[1;32m[SUCCESS]"
else
	echo -e "		\033[1;31m[FAILURE]"
fi
echo -ne "\033[1;97mfile in subdirectory "
if [ "$(cat subdir/subdirfile.h)" = "TEST-STAMP" ]; then
	echo -e "		\033[1;32m[SUCCESS]"
else
	echo -e "		\033[1;31m[FAILURE]"
fi
echo -ne "\033[1;97mshould-not-stamp file "
if [ "$(cat should-not-stamp)" = "" ]; then
	echo -e "		\033[1;32m[SUCCESS]"
else
	echo -e "		\033[1;31m[FAILURE]"
fi

# cleanup
rm -rf rootfile.c
rm -rf subdir
rm -rf .stamp
rm -rf .stamplist
rm -rf should-not-stamp
