#!/bin/bash

# generate
touch rootfile.c
mkdir subdir
touch subdir/subdirfile.h
touch .stamp
touch .stamplist

# fill
echo "TEST-STAMP" > .stamp
echo "rootfile.c" >> .stamplist
echo "subdir/subdirfile.h" >> .stamplist

# tests
echo -e "\n\033[1;97mTesting \033[1;32mstamper\033[1;97m script\n"
../stamper
echo "Stamps (2):"
if [ "$(cat rootfile.c)" = "TEST-STAMP" ]; then
	echo -e "	\033[1;32msuccess"
else
	echo -e "	\033[1;31mfailure"
fi
if [ "$(cat subdir/subdirfile.h)" = "TEST-STAMP" ]; then
	echo -e "	\033[1;32msuccess"
else
	echo -e "	\033[1;31mfailure"
fi

# clean
rm -rf rootfile.c
rm -rf subdir
rm -rf .stamp
rm -rf .stamplist
